### ISSUE TITLE
Upgrade to Beta

### ISSUE THREAD

**Issue by codefoster** [robianmcd/ng2-movies#1]
This project is my northstar :) Would love an upgrade to beta so I don't get off course in my learning. Thanks for the great learning project.

**Comment by robianmcd** [comment]
glad you've found it useful. I'll try to get this upgraded to the beta on monday

**Comment by robianmcd** [comment]
Ok it's upgraded to the beta. Had to make some weird changes though. Still looking for a better way to get the http service working and the `getFilteredMovies()` function working.

**Comment by codefoster** [comment]
Awesome!
